services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzeria
      MYSQL_USER: chef
      MYSQL_PASSWORD: pizza
    ports:
      - "3306:3306"

  app:
    image: pizzeria-be:latest
    container_name: pizzeria-be
    depends_on:
      - db
    ports:
      - "8080:8080"