spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pizzeria
    username: root
    password: root

  profiles:
    active: production

  devtools:
    livereload:
      enabled: false
    restart:
      quiet-period: 900

  jpa:
    properties:
      hibernate:
        integrator_provider: org.pizzeria.fabulosa.common.hibernate.ClassImportIntegratorIntegratorProvider
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true

      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

    open-in-view: false
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs/swagger
    operations-sorter: method

logging:
  level:
    org.hibernate: info
    org.hibernate.sql: info
    org.springframework.security: info
    org.springframework.web: info
    root: info

db:
  url: jdbc:mariadb://localhost:3306/pizzeria
  username: root
  password: root

ssl:
  keyStoreType: PKCS12
  keyStorePath: /test
  keyStorePassword: test
  keyAlias: test

security:
  tokenIssuer: http://192.168.1.128
  cookies:
    domain: 192.168.1.128
    sameSite: Lax
    httpOnly: true
    secure: false
  allowedOrigins:
    - "http://192.168.1.128:4200"
    - "http://localhost:4200"

#    trace enabled – trace, debug, info, warn and error produce log output.
#    debug enabled – debug, info, warn and error produce log output.
#    info enabled – info, warn and error produce log output.
#    warn enabled – warn and error produce log output.
#    error enabled – Only error produces log output.