INSERT INTO pizzeria.product (id, allergens, description, formats, image, name, prices, `type`)
VALUES (1, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Parmesano", "Emmental", "Queso Azul"], "en": ["Tomato Sauce", "100% Mozzarella", "Parmesan Cheese", "Emmental Cheese", "Blue Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Cuatro Quesos", "en": "Cuatro Quesos"}',
        '{"m": 13.3, "l": 18.3}', 'pizza'),
       (2, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Calabacín", "Tomate Natural", "Parmesano"], "en": ["Tomato Sauce", "100% Mozzarella", "Zucchini", "Sliced Tomato", "Parmesan Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Natura", "en": "Natura"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (3, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Cebolla", "Bacon", "Queso de Cabra"], "en": ["Tomato Sauce", "100% Mozzarella", "Onions", "Smoked Bacon", "Goat Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Cabra Loca", "en": "Cabra Loca"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (4, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Doble Mozzarella 100%", "Doble de Peperoni"], "en": ["Tomato Sauce", "Double 100% Mozzarella", "Double Pepperoni"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Roni Pepperoni", "en": "Roni Pepperoni"}',
        '{"m": 13.3, "l": 18.3}', 'pizza'),
       (5, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Nata", "Mozzarella 100%", "Cebolla", "Champiñon Fresco", "Doble de Bacon"], "en": ["Cream Sauce", "100% Mozzarella", "Onion", "Mushroom", "Double Smoked Bacon"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Carbonara", "en": "Carbonara"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (6, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Calabacín", "Champiñon Fresco", "Pollo", "Aceite de Trufa"], "en": ["Tomato Sauce", "100% Mozzarella", "Zucchini", "Mushroom", "Chicken", "White Truffle Oil"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Trufa Gourmet", "en": "Trufa Gourmet"}',
        '{"m": 14.75, "l": 20.25}', 'pizza'),
       (7, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Berenjena", "Calabacín", "Tomate Natural", "Aceitunas Negras"], "en": ["Tomato Sauce", "100% Mozzarella", "Eggplant", "Zucchini", "Sliced Tomato", "Black Olives"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Mediterránea", "en": "Mediterránea"}',
        '{"m": 14.75, "l": 20.25}', 'pizza'),
       (8, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Jamón York", "Bacon", "Peperoni", "Ternera"], "en": ["Tomato Sauce", "100% Mozzarella", "York Ham", "Smoked Bacon", "Pepperoni", "Beef"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Caníbal", "en": "Caníbal"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (9, '{"es": ["Lactosa"], "en": ["Lactose"]}',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Jamón York", "Bacon", "Peperoni"], "en": ["Tomato Sauce", "100% Mozzarella", "York Ham", "Smoked Bacon", "Pepperoni"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        '/assets/products/pizza/pizzaProduct.webp', '{"es": "Sin Gluten", "en": "Gluten Free"}',
        '{"m": 14.75, "l": 20.25}', 'pizza'),
       (11, '{"es": [], "en": []}', '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        '/assets/products/beverages/cocacola_zero.png', '{"es": "Coca-Cola Zero", "en": "Coca-Cola Zero"}',
        '{"s": 1.95, "m": 2.95}', 'beverage');
INSERT INTO pizzeria.product (id, allergens, description, formats, image, name, prices, `type`)
VALUES (12, '{"es": [], "en": []}', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', '/assets/products/beverages/fanta.png',
        '{"es": "Fanta Naranja", "en": "Fanta Orange"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (13, '{"es": [], "en": []}', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', '/assets/products/beverages/nestea.jpg',
        '{"es": "Nestea Limón", "en": "Nestea Lime"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (14, '{"es": [], "en": []}', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', '/assets/products/beverages/sprite.jpg',
        '{"es": "Sprite", "en": "Sprite"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (15, '{"es": [], "en": []}', '{"es": ["Azúcar"], "en": ["Sugar"]}', '{"s": {"es":"330ML", "en":"330ML"}}',
        '/assets/products/beverages/aquarius.jpg', '{"es": "Aquarius Limón", "en": "Aquarius Lime"}', '{"s": 1.95}',
        'beverage'),
       (16, '{"es": ["Gluten", "Alcohol"], "en": ["Gluten", "Alcohol"]}', '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}', '/assets/products/beverages/mahou-clasica.jpg',
        '{"es": "Mahou Clásica", "en": "Mahou Classic"}', '{"s": 1.95}', 'beverage'),
       (17, '{"es": ["Gluten"], "en": ["Gluten"]}', '{"es": [], "en": []}', '{"s": {"es":"330ML", "en":"330ML"}}',
        '/assets/products/beverages/mahou_sin.png', '{"es": "Mahou Sin", "en": "Mahou Without Alcohol"}', '{"s": 1.95}',
        'beverage'),
       (18, '{"es": ["Alcohol"], "en": ["Alcohol"]}', '{"es": [], "en": []}', '{"s": {"es":"330ML", "en":"330ML"}}',
        '/assets/products/beverages/mahou_sin_gluten.jpeg', '{"es": "Mahou Sin Gluten", "en": "Mahou Gluten Free"}',
        '{"s": 1.95}', 'beverage');