INSERT INTO pizzeria.product (id, allergens, code, description, formats, image, name, prices, product_type)
VALUES (1, '{"es": ["Gluten", "Huevos", "Lactosa"], "en": ["Gluten", "Eggs", "Lactose"]}', 'P1C',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Parmesano", "Emmental", "Queso Azul"], "en": ["Tomato Sauce", "100% Mozzarella", "Parmesan Cheese", "Emmental Cheese", "Blue Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Cuatro Quesos", "en": "Cuatro Quesos"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (2, '{"es": ["Gluten", "Huevos", "Lactosa"], "en": ["Gluten", "Eggs", "Lactose"]}', 'P2C',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Calabacín", "Tomate Natural", "Parmesano"], "en": ["Tomato Sauce", "100% Mozzarella", "Zucchini", "Sliced Tomato", "Parmesan Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Natura", "en": "Natura"}', '{"m": 13.3, "l": 18.3}', 'pizza'),
       (3, '{"es": ["Gluten", "Soja", "Lactosa"], "en": ["Gluten", "Soy", "Lactose"]}', 'P3C',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Cebolla", "Bacon", "Queso de Cabra"], "en": ["Tomato Sauce", "100% Mozzarella", "Onions", "Smoked Bacon", "Goat Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Cabra Loca", "en": "Cabra Loca"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (4, '{"es": ["Gluten", "Soja", "Lactosa", "Mostaza"], "en": ["Gluten", "Soy", "Lactose", "Mustard"]}', 'P4C',
        '{"es": ["Salsa de Tomate", "Doble de Mozzarella 100%", "Doble de Peperoni"], "en": ["Tomato Sauce", "Double 100% Mozzarella", "Double Pepperoni"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Roni Pepperoni", "en": "Roni Pepperoni"}', '{"m": 13.3, "l": 18.3}',
        'pizza'),
       (5, '{"es": ["Gluten", "Soja", "Lactosa"], "en": ["Gluten", "Soy", "Lactose"]}', 'P5G',
        '{"es": ["Salsa de Nata", "Mozzarella 100%", "Cebolla", "Champiñon Fresco", "Doble de Bacon"], "en": ["Cream Sauce", "100% Mozzarella", "Onion", "Mushroom", "Double Smoked Bacon"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Carbonara", "en": "Carbonara"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (6, '{"es": ["Gluten", "Soja", "Lactosa"], "en": ["Gluten", "Soy", "Lactose"]}', 'P6G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Calabacín", "Champiñon Fresco", "Pollo", "Aceite de Trufa"], "en": ["Tomato Sauce", "100% Mozzarella", "Zucchini", "Mushroom", "Chicken", "White Truffle Oil"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Trufa Gourmet", "en": "Trufa Gourmet"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (7, '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}', 'P7G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Berenjena", "Calabacín", "Tomate Natural", "Aceitunas Negras"], "en": ["Tomato Sauce", "100% Mozzarella", "Eggplant", "Zucchini", "Sliced Tomato", "Black Olives"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Mediterránea", "en": "Mediterránea"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (8, '{"es": ["Gluten", "Soja", "Lactosa", "Mostaza"], "en": ["Gluten", "Soy", "Lactose", "Mustard"]}', 'P8G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Jamón York", "Bacon", "Peperoni", "Ternera"], "en": ["Tomato Sauce", "100% Mozzarella", "York Ham", "Smoked Bacon", "Pepperoni", "Beef"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Caníbal", "en": "Caníbal"}', '{"m": 14.75, "l": 20.25}', 'pizza'),
       (9, '{"es": ["Soja", "Lactosa", "Mostaza"], "en": ["Soy", "Lactose", "Mustard"]}', 'P9G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Jamón York", "Bacon", "Peperoni"], "en": ["Tomato Sauce", "100% Mozzarella", "York Ham", "Smoked Bacon", "Pepperoni"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Sin Gluten", "en": "Gluten Free"}', '{"m": 14.75, "l": 20.25}',
        'pizza'),
       (10, '{"es": [], "en": []}', 'B1N', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', 'https://i.imgur.com/1BzVHZT.png',
        '{"es": "Coca-Cola Clásica", "en": "Coca-Cola Classic"}', '{"s": 1.95, "m": 2.95}', 'beverage');
INSERT INTO pizzeria.product (id, allergens, code, description, formats, image, name, prices, product_type)
VALUES (11, '{"es": [], "en": []}', 'B2N', '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', 'https://i.imgur.com/Nfvl5TU.png',
        '{"es": "Coca-Cola Zero", "en": "Coca-Cola Zero"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (12, '{"es": [], "en": []}', 'B3N', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', 'https://i.imgur.com/cmW3aYq.png',
        '{"es": "Fanta Naranja", "en": "Fanta Orange"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (13, '{"es": [], "en": []}', 'B4N', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', 'https://i.imgur.com/obYpRq6.jpg',
        '{"es": "Nestea Limón", "en": "Nestea Lime"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (14, '{"es": [], "en": []}', 'B5N', '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}', 'https://i.imgur.com/uCmMiKI.jpg',
        '{"es": "Sprite", "en": "Sprite"}', '{"s": 1.95, "m": 2.95}', 'beverage'),
       (15, '{"es": [], "en": []}', 'B6N', '{"es": ["Azúcar"], "en": ["Sugar"]}', '{"s": {"es":"330ML", "en":"330ML"}}',
        'https://i.imgur.com/ejlEnRd.jpg', '{"es": "Aquarius Limón", "en": "Aquarius Lime"}', '{"s": 1.95}',
        'beverage'),
       (16, '{"es": ["Gluten", "Alcohol"], "en": ["Gluten", "Alcohol"]}', 'B1A', '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}', 'https://i.imgur.com/vCIvzF8.jpg',
        '{"es": "Mahou Clásica", "en": "Mahou Classic"}', '{"s": 1.95}', 'beverage'),
       (17, '{"es": ["Gluten"], "en": ["Gluten"]}', 'B7N', '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}', 'https://i.imgur.com/C6ZW6h8.png',
        '{"es": "Mahou Sin", "en": "Mahou Without Alcohol"}', '{"s": 1.95}', 'beverage'),
       (18, '{"es": ["Alcohol"], "en": ["Alcohol"]}', 'B8N', '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}', 'https://i.imgur.com/02tKe7t.jpeg',
        '{"es": "Mahou Sin Gluten", "en": "Mahou Gluten Free"}', '{"s": 1.95}', 'beverage');