INSERT INTO pizzeria.product (id, code, description, formats, image, name, prices, product_type, allergens)
VALUES (1,
        'P1C',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Parmesano", "Emmental", "Queso Azul"], "en": ["Tomato Sauce", "100% Mozzarella", "Parmesan Cheese", "Emmental Cheese", "Blue Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Cuatro Quesos", "en": "Cuatro Quesos"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        '{"es": ["Gluten", "Huevos", "Lactosa"], "en": ["Gluten", "Eggs", "Lactose"]}'),
       (2,
        'P2C',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Calabacín", "Tomate Natural", "Parmesano"], "en": ["Tomato Sauce", "100% Mozzarella", "Zucchini", "Sliced Tomato", "Parmesan Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg', '{"es": "Natura", "en": "Natura"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        '{"es": ["Gluten", "Huevos", "Lactosa"], "en": ["Gluten", "Eggs", "Lactose"]}'),
       (3,
        'P3C',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Cebolla", "Bacon", "Queso de Cabra"], "en": ["Tomato Sauce", "100% Mozzarella", "Onions", "Smoked Bacon", "Goat Cheese"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Cabra Loca", "en": "Cabra Loca"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza', '{"es": ["Gluten", "Soja", "Lactosa"], "en": ["Gluten", "Soy", "Lactose"]}'),
       (4,
        'P4C',
        '{"es": ["Salsa de Tomate", "Doble de Mozzarella 100%", "Doble de Peperoni"], "en": ["Tomato Sauce", "Double 100% Mozzarella", "Double Pepperoni"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Roni Pepperoni", "en": "Roni Pepperoni"}',
        '{"m": 13.3, "l": 18.3}',
        'pizza',
        '{"es": ["Gluten", "Soja", "Lactosa", "Mostaza"], "en": ["Gluten", "Soy", "Lactose", "Mustard"]}'),
       (5,
        'P5G',
        '{"es": ["Salsa de Nata", "Mozzarella 100%", "Cebolla", "Champiñon Fresco", "Doble de Bacon"], "en": ["Cream Sauce", "100% Mozzarella", "Onion", "Mushroom", "Double Smoked Bacon"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Carbonara", "en": "Carbonara"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        '{"es": ["Gluten", "Soja", "Lactosa"], "en": ["Gluten", "Soy", "Lactose"]}'),
       (6,
        'P6G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Calabacín", "Champiñon Fresco", "Pollo", "Aceite de Trufa"], "en": ["Tomato Sauce", "100% Mozzarella", "Zucchini", "Mushroom", "Chicken", "White Truffle Oil"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Trufa Gourmet", "en": "Trufa Gourmet"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        '{"es": ["Gluten", "Soja", "Lactosa"], "en": ["Gluten", "Soy", "Lactose"]}'),
       (7,
        'P7G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Berenjena", "Calabacín", "Tomate Natural", "Aceitunas Negras"], "en": ["Tomato Sauce", "100% Mozzarella", "Eggplant", "Zucchini", "Sliced Tomato", "Black Olives"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Mediterránea", "en": "Mediterránea"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        '{"es": ["Gluten", "Lactosa"], "en": ["Gluten", "Lactose"]}'),
       (8,
        'P8G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Jamón York", "Bacon", "Peperoni", "Ternera"], "en": ["Tomato Sauce", "100% Mozzarella", "York Ham", "Smoked Bacon", "Pepperoni", "Beef"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Caníbal", "en": "Caníbal"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        '{"es": ["Gluten", "Soja", "Lactosa", "Mostaza"], "en": ["Gluten", "Soy", "Lactose", "Mustard"]}'),
       (9,
        'P9G',
        '{"es": ["Salsa de Tomate", "Mozzarella 100%", "Jamón York", "Bacon", "Peperoni"], "en": ["Tomato Sauce", "100% Mozzarella", "York Ham", "Smoked Bacon", "Pepperoni"]}',
        '{"m": {"es": "Mediana", "en":"Medium"}, "l": {"es": "Familiar", "en": "Large"}}',
        'https://i.imgur.com/loYe1jf.jpg',
        '{"es": "Sin Gluten", "en": "Gluten Free"}',
        '{"m": 14.75, "l": 20.25}',
        'pizza',
        '{"es": ["Soja", "Lactosa", "Mostaza"], "en": ["Soy", "Lactose", "Mustard"]}'),
       (10,
        'B1N',
        '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/1BzVHZT.png',
        '{"es": "Coca-Cola Clásica", "en": "Coca-Cola Classic"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        '{"es": [], "en": []}'),
       (11,
        'B2N',
        '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/Nfvl5TU.png',
        '{"es": "Coca-Cola Zero", "en": "Coca-Cola Zero"}', '{"s": 1.95, "m": 2.95}',
        'beverage',
        '{"es": [], "en": []}';
INSERT INTO pizzeria.product (id, code, description, formats, image, name, prices, product_type, allergens)
VALUES (12,
        'B3N',
        '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/cmW3aYq.png',
        '{"es": "Fanta Naranja", "en": "Fanta Orange"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        '{"es": [], "en": []}'),
       (13,
        'B4N',
        '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/obYpRq6.jpg',
        '{"es": "Nestea Limón", "en": "Nestea Lime"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        '{"es": [], "en": []}'),
       (14, 'B5N',
        '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}, "m": {"es":"1L", "en": "1L"}}',
        'https://i.imgur.com/uCmMiKI.jpg',
        '{"es": "Sprite", "en": "Sprite"}',
        '{"s": 1.95, "m": 2.95}',
        'beverage',
        '{"es": [], "en": []}'),
       (15,
        'B6N',
        '{"es": ["Azúcar"], "en": ["Sugar"]}',
        '{"s": {"es":"330ML", "en":"330ML"}}',
        'https://i.imgur.com/ejlEnRd.jpg',
        '{"es": "Aquarius Limón", "en": "Aquarius Lime"}',
        '{"s": 1.95}',
        'beverage',
        '{"es": [], "en": []}'),
       (16, 'B1A',
        '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}',
        'https://i.imgur.com/vCIvzF8.jpg',
        '{"es": "Mahou Clásica", "en": "Mahou Classic"}',
        '{"s": 1.95}',
        'beverage',
        '{"es": ["Gluten", "Alcohol"], "en": ["Gluten", "Alcohol"]}'),
       (17,
        'B7N',
        '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}',
        'https://i.imgur.com/C6ZW6h8.png',
        '{"es": "Mahou Sin", "en": "Mahou Without Alcohol"}',
        '{"s": 1.95}',
        'beverage',
        '{"es": ["Gluten"], "en": ["Gluten"]}'),
       (18,
        'B8N',
        '{"es": [], "en": []}',
        '{"s": {"es":"330ML", "en":"330ML"}}',
        'https://i.imgur.com/02tKe7t.jpeg',
        '{"es": "Mahou Sin Gluten", "en": "Mahou Gluten Free"}',
        '{"s": 1.95}',
        'beverage',
        '{"es": ["Alcohol"], "en": ["Alcohol"]}');